### ISSUE TITLE
The container can not start: error "task: non-zero exit (1)"

### ISSUE THREAD

**Issue by zyph00** [codesuki/ecs-nginx-proxy#19]
I'm trying to set up the nginx proxy on my Amazon AWS Docker instance together with a pimcore instance. This is my compose file:

```
version: '3.4'

services:  
  nginx-proxy:
    image: codesuki/ecs-nginx-proxy
    ports:
      - "80:80"
  pimcore-jcii:
    image: ****/pimcore5:current
    ports:
      - "8000:80"
    links:
      - "db"
    volumes:
      - efs-storage:/data
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"

volumes:
  efs-storage:
    driver: cloudstor:aws
    driver_opts:
      backing: shared
```

If I deploy this stack the nginx proxy container can not start. It appears the following error message:
`task: non-zero exit (1)`

What am I doing wrong?
